=== DzhanaevArtur/multiAgents/target/classes/dtdAndXml/pr6self.dtd
<!ELEMENT pr6ex (Professors, Students)>
<!ELEMENT Professors (Professor*)>
<!ELEMENT Professor (Time)>
<!ELEMENT Students (Student*)>
<!ELEMENT Student (Time)>
<!ELEMENT Time (#PCDATA)>

<!ATTLIST Professor name CDATA #REQUIRED>
<!ATTLIST Student name CDATA #REQUIRED>

=== DzhanaevArtur/multiAgents/pr6self.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pr6ex SYSTEM "pr6self.dtd">
<pr6ex>
    <Professors>
        <Professor name="Professor">
            <Time>17</Time>
        </Professor>
    </Professors>
    <Students>
        <Student name="Student1">
            <Time>17</Time>
        </Student>
        <Student name="Student2">
            <Time>17</Time>
        </Student>
        <Student name="Student3">
            <Time>17</Time>
        </Student>
        <Student name="Student4">
            <Time>17</Time>
        </Student>
    </Students>
</pr6ex>
