=== DzhanaevArtur/multiAgents/names.dtd
<!ELEMENT Lab3 (Agent)>
<!ELEMENT Agent (Neighbor)>
<!ELEMENT Neighbor (length)>
<!ELEMENT length (#PCDATA)>

<!ATTLIST Agent id CDATA #REQUIRED>
<!ATTLIST Neighbor id CDATA #REQUIRED>

<!ENTITY lost "Lost in the depths of time.">
<!ENTITY eacute "&#233;">

=== DzhanaevArtur/multiAgents/src/main/resources/dtdAndXml/names.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Lab3 SYSTEM "names.dtd">
<Lab3>
    <Agent id="Node1" initiator="true" final="Node12">
        <Neighbor id="Node2"><length>12</length></Neighbor>
        <Neighbor id="Node3"><length>22</length></Neighbor>
        <Neighbor id="Node4"><length>1</length></Neighbor>
        <Neighbor id="Node5"><length>2</length></Neighbor>
    </Agent>

    <Agent id="Node2" initiator="false" final="">
        <Neighbor id="Node1"><length>12</length></Neighbor>
        <Neighbor id="Node3"><length>20</length></Neighbor>
        <Neighbor id="Node4"><length>24</length></Neighbor>
        <Neighbor id="Node5"><length>17</length></Neighbor>
    </Agent>

    <Agent id="Node3" initiator="false" final="">
        <Neighbor id="Node1"><length>22</length></Neighbor>
        <Neighbor id="Node2"><length>20</length></Neighbor>
        <Neighbor id="Node4"><length>3</length></Neighbor>
        <Neighbor id="Node5"><length>14</length></Neighbor>
    </Agent>

    <Agent id="Node4" initiator="false" final="">
        <Neighbor id="Node1"><length>1</length></Neighbor>
        <Neighbor id="Node2"><length>24</length></Neighbor>
        <Neighbor id="Node3"><length>3</length></Neighbor>
        <Neighbor id="Node5"><length>16</length></Neighbor>
        <Neighbor id="Node6"><length>23</length></Neighbor>
        <Neighbor id="Node7"><length>1</length></Neighbor>
        <Neighbor id="Node8"><length>25</length></Neighbor>
    </Agent>

    <Agent id="Node5" initiator="false" final="">
        <Neighbor id="Node1"><length>2</length></Neighbor>
        <Neighbor id="Node2"><length>17</length></Neighbor>
        <Neighbor id="Node3"><length>14</length></Neighbor>
        <Neighbor id="Node4"><length>16</length></Neighbor>
        <Neighbor id="Node6"><length>22</length></Neighbor>
        <Neighbor id="Node7"><length>24</length></Neighbor>
        <Neighbor id="Node8"><length>25</length></Neighbor>
    </Agent>

    <Agent id="Node6" initiator="false" final="">
        <Neighbor id="Node4"><length>23</length></Neighbor>
        <Neighbor id="Node5"><length>22</length></Neighbor>
        <Neighbor id="Node7"><length>1</length></Neighbor>
        <Neighbor id="Node8"><length>12</length></Neighbor>
        <Neighbor id="Node9"><length>23</length></Neighbor>
    </Agent>

    <Agent id="Node7" initiator="false" final="">
        <Neighbor id="Node4"><length>1</length></Neighbor>
        <Neighbor id="Node5"><length>24</length></Neighbor>
        <Neighbor id="Node6"><length>1</length></Neighbor>
        <Neighbor id="Node8"><length>12</length></Neighbor>
        <Neighbor id="Node9"><length>1</length></Neighbor>
    </Agent>

    <Agent id="Node8" initiator="false" final="">
        <Neighbor id="Node4"><length>25</length></Neighbor>
        <Neighbor id="Node5"><length>25</length></Neighbor>
        <Neighbor id="Node6"><length>12</length></Neighbor>
        <Neighbor id="Node7"><length>12</length></Neighbor>
        <Neighbor id="Node9"><length>18</length></Neighbor>
    </Agent>

    <Agent id="Node9" initiator="false" final="">
        <Neighbor id="Node6"><length>23</length></Neighbor>
        <Neighbor id="Node7"><length>1</length></Neighbor>
        <Neighbor id="Node8"><length>18</length></Neighbor>
        <Neighbor id="Node10"><length>24</length></Neighbor>
        <Neighbor id="Node11"><length>17</length></Neighbor>
        <Neighbor id="Node12"><length>2</length></Neighbor>
    </Agent>

    <Agent id="Node10" initiator="false" final="">
        <Neighbor id="Node9"><length>24</length></Neighbor>
        <Neighbor id="Node11"><length>10</length></Neighbor>
        <Neighbor id="Node12"><length>11</length></Neighbor>
    </Agent>

    <Agent id="Node11" initiator="false" final="">
        <Neighbor id="Node9"><length>17</length></Neighbor>
        <Neighbor id="Node10"><length>10</length></Neighbor>
        <Neighbor id="Node12"><length>17</length></Neighbor>
    </Agent>

    <Agent id="Node12" initiator="false" final="">
        <Neighbor id="Node9"><length>2</length></Neighbor>
        <Neighbor id="Node10"><length>11</length></Neighbor>
        <Neighbor id="Node11"><length>17</length></Neighbor>
    </Agent>
</Lab3>

=== DzhanaevArtur/multiAgents/config.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE Lab3 SYSTEM "names.dtd">
<Lab3>
    <Agent id="Agent1">
        <Neighbor id="Agent2"><length>12</length></Neighbor>
        <Neighbor id="Agent3"><length>22</length></Neighbor>
        <Neighbor id="Agent4"><length>1</length></Neighbor>
        <Neighbor id="Agent5"><length>2</length></Neighbor>
    </Agent>

    <Agent id="Agent2">
        <Neighbor id="Agent1"><length>12</length></Neighbor>
        <Neighbor id="Agent3"><length>20</length></Neighbor>
        <Neighbor id="Agent4"><length>24</length></Neighbor>
        <Neighbor id="Agent5"><length>17</length></Neighbor>
    </Agent>

    <Agent id="Agent3">
        <Neighbor id="Agent1"><length>22</length></Neighbor>
        <Neighbor id="Agent2"><length>20</length></Neighbor>
        <Neighbor id="Agent4"><length>3</length></Neighbor>
        <Neighbor id="Agent5"><length>14</length></Neighbor>
    </Agent>

    <Agent id="Agent4">
        <Neighbor id="Agent1"><length>1</length></Neighbor>
        <Neighbor id="Agent2"><length>24</length></Neighbor>
        <Neighbor id="Agent3"><length>3</length></Neighbor>
        <Neighbor id="Agent5"><length>16</length></Neighbor>
        <Neighbor id="Agent6"><length>23</length></Neighbor>
        <Neighbor id="Agent7"><length>1</length></Neighbor>
        <Neighbor id="Agent8"><length>25</length></Neighbor>
    </Agent>

    <Agent id="Agent5">
        <Neighbor id="Agent1"><length>2</length></Neighbor>
        <Neighbor id="Agent2"><length>17</length></Neighbor>
        <Neighbor id="Agent3"><length>14</length></Neighbor>
        <Neighbor id="Agent4"><length>16</length></Neighbor>
        <Neighbor id="Agent6"><length>22</length></Neighbor>
        <Neighbor id="Agent7"><length>24</length></Neighbor>
        <Neighbor id="Agent8"><length>25</length></Neighbor>
    </Agent>

    <Agent id="Agent6">
        <Neighbor id="Agent4"><length>23</length></Neighbor>
        <Neighbor id="Agent5"><length>22</length></Neighbor>
        <Neighbor id="Agent7"><length>1</length></Neighbor>
        <Neighbor id="Agent8"><length>12</length></Neighbor>
        <Neighbor id="Agent9"><length>23</length></Neighbor>
    </Agent>

    <Agent id="Agent7">
        <Neighbor id="Agent4"><length>1</length></Neighbor>
        <Neighbor id="Agent5"><length>24</length></Neighbor>
        <Neighbor id="Agent6"><length>1</length></Neighbor>
        <Neighbor id="Agent8"><length>12</length></Neighbor>
        <Neighbor id="Agent9"><length>1</length></Neighbor>
    </Agent>

    <Agent id="Agent8">
        <Neighbor id="Agent4"><length>25</length></Neighbor>
        <Neighbor id="Agent5"><length>25</length></Neighbor>
        <Neighbor id="Agent6"><length>12</length></Neighbor>
        <Neighbor id="Agent7"><length>12</length></Neighbor>
        <Neighbor id="Agent9"><length>18</length></Neighbor>
    </Agent>

    <Agent id="Agent9">
        <Neighbor id="Agent6"><length>23</length></Neighbor>
        <Neighbor id="Agent7"><length>1</length></Neighbor>
        <Neighbor id="Agent8"><length>18</length></Neighbor>
        <Neighbor id="Agent10"><length>24</length></Neighbor>
        <Neighbor id="Agent11"><length>17</length></Neighbor>
        <Neighbor id="Agent12"><length>2</length></Neighbor>
    </Agent>

    <Agent id="Agent10">
        <Neighbor id="Agent9"><length>24</length></Neighbor>
        <Neighbor id="Agent11"><length>10</length></Neighbor>
        <Neighbor id="Agent12"><length>11</length></Neighbor>
    </Agent>

    <Agent id="Agent11">
        <Neighbor id="Agent9"><length>17</length></Neighbor>
        <Neighbor id="Agent10"><length>10</length></Neighbor>
        <Neighbor id="Agent12"><length>17</length></Neighbor>
    </Agent>

    <Agent id="Agent12">
        <Neighbor id="Agent9"><length>2</length></Neighbor>
        <Neighbor id="Agent10"><length>11</length></Neighbor>
        <Neighbor id="Agent11"><length>17</length></Neighbor>
    </Agent>
</Lab3>
